name: shell commands

on: [push]

jobs:
  run-shell-command:
    runs-on: ubuntu-latest
    steps:
      - name: echo string 
        run: echo "hello sainath your github actions ran"
      - name: multiline scripts 
        run: |
          node -v
          npm -v
          python --version