#python command run
#listing files and pwd of github runner VM
#cloning current repo into VM (in working dir)
#env variables
name: shell commands

on: [push]

jobs:
  sai-run-shell-command: #job no 1 can be given any name
    runs-on: ubuntu-latest
    steps:
      - name: echo string 
        run: echo "hello sainath your github actions ran"
      - name: multiline scripts 
        run: |
          node -v
          npm -v
          python --version
      - name: python command
        run: |
          import platform
          print(platform.processor())
        shell: python #telling to run on python shell 
  run-windows-command: # job no 2 runs parallely if we dont specify "needs"
    runs-on: windows-latest
    needs: [sai-run-shell-command] # to run sequntially pass an aarray of job ids this job will run only after all the jobs in the array pass
    steps:
      - name: Directory Powershell
        run: Get-Location
      - name: Directory Bash
        run: pwd
        shell: bash
  get-pwd-and-list-files:
    runs-on: ubuntu-latest
    needs: [sai-run-shell-command,run-windows-command]
    steps:
      - name: list files 
        id: listFiles # using this ID we can reference this step anytime we want
        run: |
          pwd
          ls -a
      - name: Checkout 
        uses: actions/checkout@v2 #git clone the commit of current repo which trigger current workflow to run, we can also clone other repo too
      - name: list files post cloning ie.Checkout
        run: |
          pwd
          ls -a
      - name: List ENV variables
        run: |
          echo $GITHUB_SHA
          echo $GITHUB_REPOSITORY
          echo $GITHUB_WORKSPACE
      - name: using custom env variables
        run: echo Hello $FIRST_NAME from $Country!
        env:
          FIRST_NAME: Sainath
          Country: India
